#!/usr/bin/env npx tsx
/**
 * Config Wizard Script
 *
 * Used by the /ops:config skill to create and manage ~/.ops/config.yaml
 *
 * Modes:
 *   show    - Display current config (or absence thereof)
 *   create  - Create config from JSON input (piped from stdin)
 *
 * Usage:
 *   npx tsx src/scripts/config-wizard.ts show
 *   echo '{"azure":{"organization":"MyOrg"}}' | npx tsx src/scripts/config-wizard.ts create
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { homedir } from 'os';
import { join, dirname } from 'path';
import { stringify as toYAML, parse as parseYAML } from 'yaml';
import { OpsConfigSchema, type OpsConfig } from '../config/schema.js';

const CONFIG_DIR = join(homedir(), '.ops');
const CONFIG_PATH = join(CONFIG_DIR, 'config.yaml');

/**
 * Show current config or indicate it doesn't exist
 */
function showConfig(): void {
  if (!existsSync(CONFIG_PATH)) {
    console.log('--- CONFIG STATUS ---');
    console.log('No config file exists at:', CONFIG_PATH);
    console.log('\nTo create a config, use the "create" mode with JSON input.');
    console.log('Required: azure.organization');
    console.log('\nExample JSON input:');
    console.log(JSON.stringify({
      azure: { organization: 'YourOrg', default_project: 'YourProject' },
      user: { name: 'Your Name', role: 'Developer', team: 'Your Team' }
    }, null, 2));
    return;
  }

  try {
    const content = readFileSync(CONFIG_PATH, 'utf-8');
    console.log('--- CURRENT CONFIG ---');
    console.log('Path:', CONFIG_PATH);
    console.log('\n--- Content ---');
    console.log(content);

    // Also validate it
    const parsed = parseYAML(content);
    const result = OpsConfigSchema.safeParse(parsed);
    if (result.success) {
      console.log('\n--- Status ---');
      console.log('Config is valid.');
    } else {
      console.log('\n--- Status ---');
      console.log('WARNING: Config has validation errors:');
      console.log(result.error.message);
    }
  } catch (error) {
    console.error('Error reading config:', error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

/**
 * Create or update config from JSON input
 */
function createConfig(): void {
  // Read JSON from stdin
  let input: string;
  try {
    input = readFileSync(0, 'utf-8').trim();
  } catch {
    console.error('Error: No input provided. Pipe JSON to stdin.');
    console.error('Example: echo \'{"azure":{"organization":"MyOrg"}}\' | npx tsx src/scripts/config-wizard.ts create');
    process.exit(1);
  }

  if (!input) {
    console.error('Error: Empty input. Provide JSON config via stdin.');
    process.exit(1);
  }

  // Parse JSON input
  let configInput: unknown;
  try {
    configInput = JSON.parse(input);
  } catch (error) {
    console.error('Error: Invalid JSON input');
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  }

  // Validate with Zod schema
  const result = OpsConfigSchema.safeParse(configInput);
  if (!result.success) {
    console.error('Error: Config validation failed');
    console.error(result.error.message);
    process.exit(1);
  }

  const config = result.data;

  // Create YAML with helpful comments
  const yamlContent = generateYAMLWithComments(config);

  // Ensure directory exists
  if (!existsSync(CONFIG_DIR)) {
    mkdirSync(CONFIG_DIR, { recursive: true });
    console.log('Created directory:', CONFIG_DIR);
  }

  // Write config file
  writeFileSync(CONFIG_PATH, yamlContent, 'utf-8');
  console.log('Config written to:', CONFIG_PATH);
  console.log('\n--- Generated Config ---');
  console.log(yamlContent);
}

/**
 * Generate YAML content with helpful comments
 */
function generateYAMLWithComments(config: OpsConfig): string {
  const lines: string[] = [];

  // Header comment
  lines.push('# Ops Configuration');
  lines.push('# Generated by /ops:config');
  lines.push('# Documentation: https://github.com/yourusername/ops');
  lines.push('');

  // Azure DevOps section
  lines.push('# Azure DevOps connection (required)');
  lines.push('azure:');
  lines.push(`  organization: ${config.azure.organization}`);
  if (config.azure.default_project) {
    lines.push(`  default_project: ${config.azure.default_project}`);
  } else {
    lines.push('  # default_project: ProjectName  # Optional: set your default project');
  }
  lines.push('');

  // User section (optional)
  lines.push('# User information (optional - for personalized briefings)');
  if (config.user) {
    lines.push('user:');
    if (config.user.name) lines.push(`  name: ${config.user.name}`);
    if (config.user.role) lines.push(`  role: ${config.user.role}`);
    if (config.user.team) lines.push(`  team: ${config.user.team}`);
  } else {
    lines.push('# user:');
    lines.push('#   name: Your Name');
    lines.push('#   role: Developer');
    lines.push('#   team: Your Team');
  }
  lines.push('');

  // VIPs section
  lines.push('# Important people to track (optional)');
  if (config.vips && config.vips.length > 0) {
    lines.push('vips:');
    for (const vip of config.vips) {
      lines.push(`  - name: ${vip.name}`);
      lines.push(`    role: ${vip.role}`);
      lines.push(`    priority: ${vip.priority}`);
    }
  } else {
    lines.push('# vips:');
    lines.push('#   - name: Manager Name');
    lines.push('#     role: Engineering Manager');
    lines.push('#     priority: high');
  }
  lines.push('');

  // Priorities section
  lines.push('# Priority weights for work item scoring');
  lines.push('priorities:');
  lines.push(`  sprint_commitment: ${config.priorities.sprint_commitment}`);
  lines.push(`  vip_involvement: ${config.priorities.vip_involvement}`);
  lines.push(`  blocking_others: ${config.priorities.blocking_others}`);
  lines.push(`  age_over_3_days: ${config.priorities.age_over_3_days}`);
  lines.push(`  p1_priority: ${config.priorities.p1_priority}`);
  lines.push(`  p2_priority: ${config.priorities.p2_priority}`);
  lines.push(`  carried_over: ${config.priorities.carried_over}`);
  lines.push('');

  // GSD section
  lines.push('# GSD (Get Stuff Done) framework settings');
  lines.push('gsd:');
  lines.push(`  scan_paths: ${JSON.stringify(config.gsd.scan_paths)}`);
  lines.push(`  exclude: ${JSON.stringify(config.gsd.exclude)}`);
  lines.push('');

  // Preferences section
  lines.push('# Output preferences');
  lines.push('preferences:');
  lines.push(`  briefing_length: ${config.preferences.briefing_length}`);
  lines.push(`  response_style: ${config.preferences.response_style}`);
  lines.push(`  timezone: ${config.preferences.timezone}`);

  return lines.join('\n') + '\n';
}

/**
 * Main entry point
 */
export function runConfigWizard(args: string[] = process.argv.slice(2)): void {
  const mode = args[0] || 'show';

  switch (mode) {
    case 'show':
      showConfig();
      break;
    case 'create':
      createConfig();
      break;
    default:
      console.error('Unknown mode:', mode);
      console.error('Usage: config-wizard.ts [show|create]');
      console.error('  show   - Display current config');
      console.error('  create - Create config from JSON input (stdin)');
      process.exit(1);
  }
}

// Run if executed directly
const isMainModule = process.argv[1]?.endsWith('config-wizard.ts') ||
                     process.argv[1]?.endsWith('config-wizard.js');
if (isMainModule) {
  runConfigWizard();
}
